In [1]:
words = open('names.txt', 'r').read().splitlines()

In [2]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
len(words)

32033

In [4]:
min(len(w) for w in words)

2

In [5]:
max(len(w) for w in words)

15

In [6]:
for w in words[:1]:
    for ch1,ch2 in zip(w, w[1:]):
        print (ch1, ch2)

e m
m m
m a


In [7]:
w

'emma'

In [8]:
list(w)

['e', 'm', 'm', 'a']

In [9]:
w[1:]

'mma'

In [10]:
for w in words[:1]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1,ch2 in zip(chs, chs[1:]):
        print(ch1,ch2)
        

<S> e
e m
m m
m a
a <E>


In [11]:
b = {}
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)    #tuple
        b[bigram] = b.get(bigram, 0) + 1
        #print(ch1,ch2)
        

In [12]:
b

{('<S>', 'e'): 1531,
 ('e', 'm'): 769,
 ('m', 'm'): 168,
 ('m', 'a'): 2590,
 ('a', '<E>'): 6640,
 ('<S>', 'o'): 394,
 ('o', 'l'): 619,
 ('l', 'i'): 2480,
 ('i', 'v'): 269,
 ('v', 'i'): 911,
 ('i', 'a'): 2445,
 ('<S>', 'a'): 4410,
 ('a', 'v'): 834,
 ('v', 'a'): 642,
 ('<S>', 'i'): 591,
 ('i', 's'): 1316,
 ('s', 'a'): 1201,
 ('a', 'b'): 541,
 ('b', 'e'): 655,
 ('e', 'l'): 3248,
 ('l', 'l'): 1345,
 ('l', 'a'): 2623,
 ('<S>', 's'): 2055,
 ('s', 'o'): 531,
 ('o', 'p'): 95,
 ('p', 'h'): 204,
 ('h', 'i'): 729,
 ('<S>', 'c'): 1542,
 ('c', 'h'): 664,
 ('h', 'a'): 2244,
 ('a', 'r'): 3264,
 ('r', 'l'): 413,
 ('l', 'o'): 692,
 ('o', 't'): 118,
 ('t', 't'): 374,
 ('t', 'e'): 716,
 ('e', '<E>'): 3983,
 ('<S>', 'm'): 2538,
 ('m', 'i'): 1256,
 ('a', 'm'): 1634,
 ('m', 'e'): 818,
 ('<S>', 'h'): 874,
 ('r', 'p'): 14,
 ('p', 'e'): 197,
 ('e', 'r'): 1958,
 ('r', '<E>'): 1377,
 ('e', 'v'): 463,
 ('v', 'e'): 568,
 ('l', 'y'): 1588,
 ('y', 'n'): 1826,
 ('n', '<E>'): 6763,
 ('b', 'i'): 217,
 ('i', 'g'): 428,


In [13]:
sorted(b.items(), key = lambda kv: -kv[1])

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [14]:
import torch

In [15]:
a = torch.zeros((3,5), dtype=torch.int32)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [16]:
a.dtype

torch.int32

In [17]:
a[1,3] += 1

In [18]:
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [19]:
N = torch.zeros((28,28), dtype=torch.int32)

In [20]:
# chars = sorted(list(set(''.join(words))))
# stoi = {s:i for i,s in enumerate(chars)}
# stoi['<S>']=26
# stoi['<E>']=27

In [21]:

# for w in words:
#     chs = ['<S>'] + list(w) + ['<E>']
#     for ch1, ch2 in zip(chs, chs[1:]):
#         ix1 = stoi[ch1]
#         ix2 = stoi[ch2]
#         N[ix1, ix2] +=1
        

In [22]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.']=0
itos = {i:s for s,i in stoi.items()}

In [23]:

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] +=1
        

In [24]:
N

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929,    0],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435,    0],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4,    0],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1,    0],
        [3983,  679,

In [25]:
# itos = {i:s for s,i in stoi.items()}

In [26]:
type(N)

torch.Tensor

In [27]:
type(N[3,3].item())

int

In [28]:
# import matplotlib.pyplot as plt
# %matplotlib inline

# plt.figure(figsize = (16,6))
# plt.imshow(N, cmap='Blues')
# for i in range(28):
#     for j in range(28):
#         chstr = itos[i] + itos[j]
#         plt.txt(j, i, chstr, ha='center', va= "bottom", color="gray")
#         plt.txt(j, i, N[i,j].item(), ha='center', va= "bottom", color="gray")
# plt.axis('off');

In [29]:
N[0,:] #N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929,    0], dtype=torch.int32)

In [30]:
p = N[0,:].float()
p = p/p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290,
        0.0000])

In [31]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p/p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [32]:
torch.multinomial(p, num_samples=20, replacement = True, generator = g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [33]:
torch.multinomial(p, num_samples=100, replacement = True, generator = g)

tensor([0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 0, 2, 0])

In [38]:
p = N[0].float()
p = p/p.sum()
g = torch.Generator().manual_seed(2147483647)
idx = torch.multinomial(p, num_samples=1, replacement=True,generator=g)
itos[int(idx)]

'c'

# Broadcasting 

In [44]:
P.sum(0, keepdim=True) #2d #1,27
#P.sum(0) #squeeze out #1d #1,27

tensor([[3.0369, 5.3447, 0.2204, 0.2657, 0.4196, 3.2649, 0.1457, 0.1697, 1.2067,
         2.7842, 0.1592, 0.3686, 1.2061, 0.4411, 1.3129, 1.4016, 0.1447, 0.0652,
         1.6448, 0.7639, 0.6089, 1.1808, 0.2000, 0.1647, 0.1425, 1.0612, 0.2277,
         0.0477]])

In [45]:
P.sum(0, keepdim=True).shape

torch.Size([1, 28])

In [46]:
P.sum(1, keepdim=True).shape #27,1
P.sum(1).shape #27 or #1,27  #it suddenly become row vector instead of column vector
#values are same but the shape is differ which will give diff output, potential bug

torch.Size([28])

In [52]:
P.sum(1, keepdim=True)

tensor([[1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000]])

In [51]:

#P = N.float()   #27,27
P = (N+1).float()   #27,27  #model smoothing
#P = P / P.sum()
#P = P / P.sum(1) #1,27
P = P / P.sum(1, keepdim=True) # 27,1 # what it do's is stretch it out, make copies to match it with 27,27 
# it is allowed until dimensions are same , like here it is 2d


In [43]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
    out = []
    ix = 0
    
    while True:
        p = P[ix]
        # p = N[ix].float()
        # p = p/p.sum()
        ix = int(torch.multinomial(p, num_samples=1, replacement=True,generator=g))
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

cava.
ayamaijowy.
aianeta.
rl.
miryndardyrioma.
kiinninaswila.
en.
ahlanyanlen.
tav.
sissth.


In [49]:
log_likelyhood = 0.0
n=0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1,ix2]    #likelyhood is the product of these prob
        logprob = torch.log(prob) # -inf to 0  #log -> so that we can sum simply
        log_likelyhood += logprob
        n+=1
        print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')
print(f'{log_likelyhood=}')
nll = -log_likelyhood
print(f'{nll=}') #loss
print(f'{nll/n}') #avg loss

.e: 0.0478 -3.0411
em: 0.0377 -3.2794
mm: 0.0253 -3.6755
ma: 0.3885 -0.9456
a.: 0.1958 -1.6305
.o: 0.0123 -4.3965
ol: 0.0779 -2.5527
li: 0.1774 -1.7294
iv: 0.0152 -4.1845
vi: 0.3506 -1.0480
ia: 0.1380 -1.9807
a.: 0.1958 -1.6305
.a: 0.1376 -1.9835
av: 0.0246 -3.7041
va: 0.2472 -1.3975
a.: 0.1958 -1.6305
log_likelyhood=tensor(-38.8102)
nll=tensor(38.8102)
2.425637722015381


In [53]:
1/27 #if set equal prob  #should greater than that , then it will mean it learned something usefull

0.037037037037037035

In [55]:
log_likelyhood = 0.0
n=0
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1,ix2]    #likelyhood is the product of these prob
        logprob = torch.log(prob) # -inf to 0  #log -> so that we can sum simply
        log_likelyhood += logprob
        n+=1
        #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')
print(f'{log_likelyhood=}')
nll = -log_likelyhood
print(f'{nll=}') #loss
print(f'{nll/n}') #avg loss

log_likelyhood=tensor(-559978.7500)
nll=tensor(559978.7500)
2.4544754028320312


In [57]:
log_likelyhood = 0.0
n=0
for w in ["andrej"]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1,ix2]    #likelyhood is the product of these prob
        logprob = torch.log(prob) # -inf to 0  #log -> so that we can sum simply
        log_likelyhood += logprob
        n+=1
        #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')
print(f'{log_likelyhood=}')
nll = -log_likelyhood
print(f'{nll=}') #loss
print(f'{nll/n}') #avg loss

log_likelyhood=tensor(-21.2582)
nll=tensor(21.2582)
3.0368807315826416


In [58]:
log_likelyhood = 0.0
n=0
for w in ["andrejq"]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1,ix2]    #likelyhood is the product of these prob
        logprob = torch.log(prob) # -inf to 0  #log -> so that we can sum simply
        log_likelyhood += logprob
        n+=1
        #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')
print(f'{log_likelyhood=}')
nll = -log_likelyhood
print(f'{nll=}') #loss
print(f'{nll/n}') #avg loss
# it will give inf  # bcz of 0 count
# which is not good, so we can do model smoothing to deal with this 

log_likelyhood=tensor(-27.8713)
nll=tensor(27.8713)
3.483914852142334


# Approach 2: NN

In [59]:
# create the training set of all the bigrams(x,y)

xs, ys = [], []
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1,ch2)
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)
        
        

. e
e m
m m
m a
a .


In [60]:
xs

tensor([ 0,  5, 13, 13,  1])

In [61]:
ys

tensor([ 5, 13, 13,  1,  0])

In [62]:
import torch.nn.functional as F
xenc = F.one_hot(xs,num_classes=27).float()
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
xenc.shape

torch.Size([5, 27])

In [68]:
import matplotlib.pyplot as plt

plt.imshow(xenc)


In [69]:
xenc.dtype

torch.float32

In [70]:
#W= torch.randn((27,1)) #1 neuron
W= torch.randn((27,27)) #27neurons
W

tensor([[-0.1103,  0.2424, -1.0547, -0.4992, -0.7885, -1.0899,  0.0081, -1.6921,
          0.0456, -1.0036, -1.3668, -0.1282,  0.9734,  0.8460,  0.3372, -0.2808,
          0.4881, -2.2531,  0.5283,  1.8994,  0.1774,  0.7150, -0.5355,  0.1708,
         -0.5226,  0.1028,  0.3965],
        [-0.3071,  0.2858, -0.1644,  1.6910,  0.2979,  0.2967,  0.5025, -2.7318,
         -0.4908,  0.4696, -0.4111, -0.4697,  0.7807, -0.1607, -1.2679, -1.6558,
          1.3480,  0.4748, -1.2252,  0.4206,  0.5770, -1.6693, -0.9836, -1.0856,
         -0.8358,  1.4019,  1.4438],
        [-0.7297, -0.8255, -0.5151,  0.2802, -1.8107,  0.9080,  0.3102,  1.0991,
         -0.0103, -1.8104, -1.2661, -0.5864, -1.2085, -0.0207, -0.9764,  0.4469,
          0.4175,  1.4144, -0.3477, -1.7478, -0.9113, -0.8179, -1.8690, -0.2428,
          1.3683, -1.8534, -1.1419],
        [-0.4007,  0.6858, -1.9226, -0.5979,  0.5008, -0.2256, -1.4330, -0.7357,
          0.6353,  0.3320, -0.1307,  1.0410,  0.5922,  0.3193, -0.6850, -0.0943

In [ ]:
xenc @ W #(5,27) @ (27,27) -> (5,27) , these 27 giving us log_counts

In [71]:
(xenc @ W).shape

torch.Size([5, 27])

In [72]:
(xenc @ W)[3,13]

tensor(0.5413)

In [73]:
(xenc @ W).exp()   #counting counts positive

tensor([[0.8956, 1.2743, 0.3483, 0.6070, 0.4545, 0.3363, 1.0081, 0.1841, 1.0467,
         0.3666, 0.2549, 0.8796, 2.6469, 2.3302, 1.4010, 0.7551, 1.6292, 0.1051,
         1.6961, 6.6817, 1.1941, 2.0441, 0.5854, 1.1863, 0.5929, 1.1083, 1.4866],
        [1.6387, 0.2454, 3.6697, 0.5414, 0.4480, 3.2743, 9.2331, 2.1193, 3.3033,
         0.2732, 0.3901, 0.2833, 1.8577, 1.3064, 0.4861, 0.6147, 0.5944, 0.4601,
         0.4134, 0.1938, 0.7721, 0.5984, 0.5457, 0.3724, 1.8622, 0.7171, 2.0688],
        [1.0081, 2.5753, 2.9469, 0.5553, 1.3045, 2.6978, 0.7035, 2.1676, 1.1255,
         0.4449, 2.0298, 0.2741, 3.1956, 1.7182, 3.2251, 0.7779, 1.4628, 0.9143,
         5.5059, 0.2170, 0.8404, 0.7173, 0.2712, 1.3674, 0.4914, 0.9560, 0.9947],
        [1.0081, 2.5753, 2.9469, 0.5553, 1.3045, 2.6978, 0.7035, 2.1676, 1.1255,
         0.4449, 2.0298, 0.2741, 3.1956, 1.7182, 3.2251, 0.7779, 1.4628, 0.9143,
         5.5059, 0.2170, 0.8404, 0.7173, 0.2712, 1.3674, 0.4914, 0.9560, 0.9947],
        [0.7356, 1.3309,

In [89]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), generator = g, requires_grad=True)

In [90]:
xenc = F.one_hot(xs, num_classes=27).float()
logits = xenc @ W
counts = logits.exp()
probs = counts / counts.sum(1,keepdims=True)
probs

tensor([[0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
         0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
         0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459],
        [0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
         0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
         0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472],
        [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
         0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
         0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
        [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
         0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
         0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
        [0.0150, 0.0086,

In [88]:
probs[0]

tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0169, 0.0126, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2372, 0.0604, 0.0025,
        0.0250, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1535, 0.1458],
       grad_fn=<SelectBackward0>)

In [91]:
xs

tensor([ 0,  5, 13, 13,  1])

In [92]:
ys

tensor([ 5, 13, 13,  1,  0])

In [93]:
probs.shape

torch.Size([5, 27])

In [94]:
probs[0,5],probs[1,13],probs[2,13],probs[3,1],probs[4,0]

(tensor(0.0123, grad_fn=<SelectBackward0>),
 tensor(0.0181, grad_fn=<SelectBackward0>),
 tensor(0.0267, grad_fn=<SelectBackward0>),
 tensor(0.0737, grad_fn=<SelectBackward0>),
 tensor(0.0150, grad_fn=<SelectBackward0>))

In [95]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [96]:
probs[torch.arange(5),ys]

tensor([0.0123, 0.0181, 0.0267, 0.0737, 0.0150], grad_fn=<IndexBackward0>)

In [97]:
loss = -probs[torch.arange(5),ys].log().mean()
loss

tensor(3.7693, grad_fn=<NegBackward0>)

In [98]:
W.grad = None #set to zero gradient
loss.backward()

In [99]:
W.data += -0.1 * W.grad